[toolchain]
channel = "1.90.0"
targets = ["x86_64-unknown-uefi", "aarch64-unknown-uefi"]
components = ["rust-src", "clippy", "rustfmt", "rust-docs"]

# A custom section for CI pipelines to install tools
[tools]
cargo-deny = "^0.17"
cargo-make = "0.37.21"
cargo-llvm-cov = "0.6.18"
cargo-release = "0.25.12"
mdbook = "0.4.40"
mdbook-mermaid = "0.14.0"
mdbook-admonish = "1.18.0"
