
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.EmbarkStudios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.OpenDevicePartnership]
url = "https://raw.githubusercontent.com/OpenDevicePartnership/rust-crate-audits/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.aarch64-cpu]]
version = "10.0.0"
criteria = "safe-to-deploy"

[[exemptions.alloc-no-stdlib]]
version = "2.0.4"
criteria = "safe-to-deploy"

[[exemptions.alloy-rlp]]
version = "0.3.12"
criteria = "safe-to-run"

[[exemptions.anes]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.ark-ff]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.ark-ff]]
version = "0.4.2"
criteria = "safe-to-run"

[[exemptions.ark-ff]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.ark-ff-asm]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.ark-ff-asm]]
version = "0.4.2"
criteria = "safe-to-run"

[[exemptions.ark-ff-asm]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.ark-ff-macros]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.ark-ff-macros]]
version = "0.4.2"
criteria = "safe-to-run"

[[exemptions.ark-ff-macros]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.ark-serialize]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.ark-serialize]]
version = "0.4.2"
criteria = "safe-to-run"

[[exemptions.ark-serialize]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.ark-std]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.ark-std]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.ark-std]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.arm-gic]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.auto_impl]]
version = "1.3.0"
criteria = "safe-to-run"

[[exemptions.bit_field]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.bitfield-struct]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.bitvec]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.brotli-decompressor]]
version = "4.0.3"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.19.0"
criteria = "safe-to-run"

[[exemptions.byte-slice-cast]]
version = "1.2.3"
criteria = "safe-to-run"

[[exemptions.cfg-if]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.5.47"
criteria = "safe-to-deploy"

[[exemptions.compile-time]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.const_format]]
version = "0.2.35"
criteria = "safe-to-run"

[[exemptions.const_format_proc_macros]]
version = "0.2.34"
criteria = "safe-to-run"

[[exemptions.crc]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.crc-catalog]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.crossbeam-epoch]]
version = "0.9.18"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-run"

[[exemptions.crunchy]]
version = "0.2.4"
criteria = "safe-to-run"

[[exemptions.crypto-common]]
version = "0.1.3"
criteria = "safe-to-run"

[[exemptions.derivative]]
version = "2.2.0"
criteria = "safe-to-run"

[[exemptions.digest]]
version = "0.9.0"
criteria = "safe-to-run"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-run"

[[exemptions.downcast]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.educe]]
version = "0.6.0"
criteria = "safe-to-run"

[[exemptions.enum-ordinalize]]
version = "4.3.0"
criteria = "safe-to-run"

[[exemptions.enum-ordinalize-derive]]
version = "4.3.1"
criteria = "safe-to-run"

[[exemptions.fallible-streaming-iterator]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.fastrlp]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.fastrlp]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.fixed-hash]]
version = "0.8.0"
criteria = "safe-to-run"

[[exemptions.fixedbitset]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.fragile]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.funty]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.gdbstub]]
version = "0.7.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.16"
criteria = "safe-to-run"

[[exemptions.half]]
version = "2.7.0"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.15.2"
criteria = "safe-to-run"

[[exemptions.heck]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.impl-codec]]
version = "0.6.0"
criteria = "safe-to-run"

[[exemptions.impl-trait-for-tuples]]
version = "0.2.3"
criteria = "safe-to-run"

[[exemptions.itertools]]
version = "0.13.0"
criteria = "safe-to-run"

[[exemptions.js-sys]]
version = "0.3.81"
criteria = "safe-to-run"

[[exemptions.libm]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.linked_list_allocator]]
version = "0.10.5"
criteria = "safe-to-deploy"

[[exemptions.lzma-rs]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.managed]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.mockall]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.mockall_derive]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.mu_rust_helpers]]
version = "3.0.2"
criteria = "safe-to-deploy"

[[exemptions.mu_uefi_decompress]]
version = "3.0.2"
criteria = "safe-to-deploy"

[[exemptions.mu_uefi_guid]]
version = "3.0.2"
criteria = "safe-to-deploy"

[[exemptions.mu_uefi_perf_timer]]
version = "3.0.2"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.1"
criteria = "safe-to-deploy"

[[exemptions.oorandom]]
version = "11.1.5"
criteria = "safe-to-run"

[[exemptions.parity-scale-codec]]
version = "3.7.5"
criteria = "safe-to-run"

[[exemptions.parity-scale-codec-derive]]
version = "3.7.5"
criteria = "safe-to-run"

[[exemptions.pest]]
version = "2.8.3"
criteria = "safe-to-run"

[[exemptions.plain]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.primitive-types]]
version = "0.12.2"
criteria = "safe-to-run"

[[exemptions.proc-macro-crate]]
version = "3.4.0"
criteria = "safe-to-run"

[[exemptions.proptest]]
version = "1.8.0"
criteria = "safe-to-run"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.radium]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.9.2"
criteria = "safe-to-run"

[[exemptions.rand_chacha]]
version = "0.9.0"
criteria = "safe-to-run"

[[exemptions.rand_core]]
version = "0.9.3"
criteria = "safe-to-run"

[[exemptions.rand_xorshift]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.raw-cpuid]]
version = "10.7.0"
criteria = "safe-to-deploy"

[[exemptions.rlp]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.ruint]]
version = "1.17.0"
criteria = "safe-to-run"

[[exemptions.ruint-macro]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.rustc-hex]]
version = "2.1.0"
criteria = "safe-to-run"

[[exemptions.rustc_version]]
version = "0.3.3"
criteria = "safe-to-run"

[[exemptions.rustc_version]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.safe-mmio]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.semver-parser]]
version = "0.10.3"
criteria = "safe-to-run"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.spinning_top]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.tock-registers]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.toml_edit]]
version = "0.23.6"
criteria = "safe-to-run"

[[exemptions.typenum]]
version = "1.19.0"
criteria = "safe-to-run"

[[exemptions.uart_16550]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.uint]]
version = "0.9.5"
criteria = "safe-to-run"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-run"

[[exemptions.valuable]]
version = "0.1.1"
criteria = "safe-to-run"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-run"

[[exemptions.volatile]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.104"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.104"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.104"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.104"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.104"
criteria = "safe-to-run"

[[exemptions.web-sys]]
version = "0.3.81"
criteria = "safe-to-run"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.windows-link]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.wit-bindgen]]
version = "0.46.0"
criteria = "safe-to-run"

[[exemptions.wyz]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.x86]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.x86_64]]
version = "0.15.2"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.8.2"
criteria = "safe-to-run"
