[net]
git-fetch-with-cli = true

[registries]
UefiRust = { index = "sparse+https://pkgs.dev.azure.com/microsoft/MsUEFI/_packaging/UefiRust/Cargo/index/" }

[source.crates-io]
replace-with = "UefiRust"
