# GitHub Issue Configuration File
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
blank_issues_enabled: false
contact_links:
  - name: ðŸ“ƒ Documentation
    url: https://OpenDevicePartnership.github.io/uefi-core/
    about: Goals, principles, repo layout, build instructions, and more.
