[package]
name = "uefi_performance"
resolver = "2"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
description = "Performance support for the DXE Core."

[lib]
name = "uefi_performance"
path = "src/lib.rs"

[dependencies]
r-efi = { workspace = true }
scroll = { workspace = true }
log = { workspace = true }
uuid = { workspace = true }

mu_pi = { workspace = true }
mu_rust_helpers = { workspace = true }
uefi_sdk = { workspace = true }

[features]
instrument_performance = []
