[package]
name = "patina_macro"
version.workspace = true
publish.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
description = "Proc-macro crate for the UEFI Software Development Kit (SDK)."

[lib]
proc-macro = true

[dependencies]
uuid = { workspace = true}
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }

[dev-dependencies]
# To avoid circular dependencies, cargo-release skips dev dependencies when evaluating the release order for
# cargo-release, however they are still used when verifying the package is compileable. Any dev-dependency that is
# local to the workspace should be added via `path` instead of `workspace = true` so that that it does not fail to
# compile due to the dev-dependency not being published yet.
patina = { path="../../sdk/patina" }


[features]
default = []
# Opting in to the `enable_patina_tests` feature requires registering at least one test
# with the `#[patina_test]` attribute. Otherwise, a linker crash or failure will
# occur!
enable_patina_tests = []
