# @file publish-release.yml
#
# A Github workflow that publishes all crates in a repository to crates.io and creates a release on
# GitHub.
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
##
name: Publish Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    uses: ./.github/workflows/ReleaseWorkflow.yml
    with:
      ignore-prefix: 'patina-v'
    secrets: inherit
    permissions:
      contents: write
      actions: read
