# @file publish-mdbook.yml
#
# A Github workflow that compiles an mdbook located at docs/* and publishes it
# to the repository's githubpages page.
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: Publish Documentation

on:
  # Trigger this workflow manually if necessary
  workflow_dispatch:

  # Triggers this workflow if a commit is pushed to main in which a file in
  # docs/** has been updated
  push:
    branches:
      - main
    paths:
      - docs/**

jobs:
  build:
    name: Build Documentation

    runs-on: ubuntu-latest

    steps:
      - name: âœ… Checkout Repository âœ…
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Download Rust Tools ğŸ› ï¸
        uses: OpenDevicePartnership/patina/.github/actions/rust-tool-cache@main

      - name: ğŸ“„ Build Documentation ğŸ“„
        run: mdbook build docs

      - name: Upload Github Pages Site Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: docs/book/

  publish:
    name: Publish Documentation

    needs: [build]

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pages: write

    steps:
      - name: ğŸš€ Deploy Github Pages Site ğŸš€
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}
          artifact_name: github-pages
