# @file rust-version-check.yml
#
# A workflow that checks for changes to the channel field in rust-toolchain.toml on pull requests.
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
##

name: Rust Version Change Detection

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths:
      - 'rust-toolchain.toml'

jobs:
  check-rust-version:
      permissions:
        pull-requests: write
        contents: read

      uses: OpenDevicePartnership/patina-devops/.github/workflows/RustVersionCheck.yml@v0.0.1
      secrets: inherit
