# This workflow assists with initial triage of new issues by applying
# labels based on data provided in the issue.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
#

name: Initial Triage for New Issue

on:
  issues:
    types: [ opened ]

jobs:
  triage:
    permissions:
      contents: read
      issues: write

    uses: ./.github/workflows/IssueTriager.yml
    secrets: inherit
